language: python
env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=disk
matrix:
  include:
  - dist: xenial
    os: linux
    python: 3.8
    env:
    - TOXENV=py38
  - os: osx
    language: generic
    if: tag IS present
    env:
    - TOXENV=py27
    - GITHUB_UPLOAD=yes
    addons:
      homebrew:
        packages: python3

# only test master and tagged releases on push
# always test things that aren't pushes (like PRs)
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/


install: pip install tox
script:
  # - if [[ $GITHUB_UPLOAD == 'yes' ]]; then python3 -m pip install -r requirements.dev.txt; fi;
  - python3 -m pip install -r requirements.dev.txt
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then tox; fi;
# Deploy to github releases, and pypi.
# https://docs.travis-ci.com/user/deployment/
# travis osx has python3.6 installed.
  # install python3 with homebrew on osx.
  # - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update ; brew upgrade python; export PATH=/usr/local/bin:$PATH; fi;
  # make a sdist and a .dmg mac installer.
  - if [[ $GITHUB_UPLOAD == 'yes' ]]; then python3 setup.py sdist; fi;
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 setup.py bdist_dmg; fi;
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "glj9+FTo4mCzxRCeGFEhOIPsR76QXDXp64ID+Aab5sZ78DpIwRfcBbOK4VmaTFRju8wnUwLoQKeU9mcImh29qBr59GhUEQcXbiV3ulf5okVxUUa5YVN58PHv16H5ZSH34xHCGfBv0Oz8OrODPxY4E9noJYkBLcLHSxSWHIvzGAkmAy6GogOhl25gVz5mrgPOl/xVvHKTqKWjYZ3nxwXldEFrGPnTecUVEFXWsotcUH/GIt+A/vc7Z2HPIa/Vb2gt9TmSeDQobliqCQogTMAu0eqD6oYUHIMfi4wTxn1T5AEjqMAJcnkGARMNGxbIYTzAJEPZtW/jUFTE3DXtnRAcBOfM4TcOA1Oo4eEhZCQ4e/DWVuUvVfUxCtrPJG9O4na7tN75FmikTfOpb4BteMAhcEUVaE40eJWuaJFoz+ok+0gC0H9wx/xG2Mk5YsgKTw6kAH2gINn/urUsNOXH2Gjs5w3V6uN31XZPMfy49zbJ/NOJke5C9ZKjXMlIEapoSKUTkN+gS0Z4B+rcnpWaJda6UyqIWOOsKGR2fsVlyZ56yYgpOeZG4LiaZABBicy6L/2ACslzS7bVVgeNwYMRgZJpT8hmVL9isX7QpQGtBCYVR0gYsPAn+7QGjwh6hUiWAj86jmRAT9prWVARrVu2Tb2jy3+S89A174LAOW8P/IV8d2s="

    file_glob: true
    file:
      - build/*.dmg
      - dist/*.tar.gz
    draft: true
    on:
      all_branches: true
      # branches:
      #   only:
      #     - master
      tag: true
      repo: pygame/stuntcat
      condition: $GITHUB_UPLOAD = yes
